//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCMuseo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escultura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Escultura()
        {
            this.EsculturaExhibicion = new HashSet<EsculturaExhibicion>();
        }
    
        public int idEscultura { get; set; }
        public string nombre { get; set; }
        public int idArtista { get; set; }
        public int idCorrienteArtistica { get; set; }
        public int idTecnicaEscultura { get; set; }
        public int idPais { get; set; }
        public int idPeriodo { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual CorrienteArtistica CorrienteArtistica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EsculturaExhibicion> EsculturaExhibicion { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual TecnicaEscultura TecnicaEscultura { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
