//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCMuseo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuseoEntities : DbContext
    {
        public MuseoEntities()
            : base("name=MuseoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<ArticuloTienda> ArticuloTienda { get; set; }
        public virtual DbSet<Artista> Artista { get; set; }
        public virtual DbSet<ArtistaEscuela> ArtistaEscuela { get; set; }
        public virtual DbSet<Audioguia> Audioguia { get; set; }
        public virtual DbSet<Boleto> Boleto { get; set; }
        public virtual DbSet<BoletoExhibicion> BoletoExhibicion { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Clasificacion> Clasificacion { get; set; }
        public virtual DbSet<CorrienteArtistica> CorrienteArtistica { get; set; }
        public virtual DbSet<DirectorDeExhibicionExterno> DirectorDeExhibicionExterno { get; set; }
        public virtual DbSet<Distribuidora> Distribuidora { get; set; }
        public virtual DbSet<Editorial> Editorial { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EmpleadoExhibicion> EmpleadoExhibicion { get; set; }
        public virtual DbSet<EmpleadoTaller> EmpleadoTaller { get; set; }
        public virtual DbSet<EmpleadoTienda> EmpleadoTienda { get; set; }
        public virtual DbSet<Escuela> Escuela { get; set; }
        public virtual DbSet<Escultura> Escultura { get; set; }
        public virtual DbSet<EsculturaExhibicion> EsculturaExhibicion { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<EventoSala> EventoSala { get; set; }
        public virtual DbSet<Exhibicion> Exhibicion { get; set; }
        public virtual DbSet<ExhibicionFotografia> ExhibicionFotografia { get; set; }
        public virtual DbSet<ExhibicionLibro> ExhibicionLibro { get; set; }
        public virtual DbSet<ExhibicionObjeto> ExhibicionObjeto { get; set; }
        public virtual DbSet<ExhibicionPelicula> ExhibicionPelicula { get; set; }
        public virtual DbSet<ExhibicionPintura> ExhibicionPintura { get; set; }
        public virtual DbSet<ExhibicionSala> ExhibicionSala { get; set; }
        public virtual DbSet<FormatoDeCamara> FormatoDeCamara { get; set; }
        public virtual DbSet<Fotografia> Fotografia { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<Objeto> Objeto { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Pelicula> Pelicula { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<Pintura> Pintura { get; set; }
        public virtual DbSet<Productora> Productora { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Regalo> Regalo { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<SalaTaller> SalaTaller { get; set; }
        public virtual DbSet<Taller> Taller { get; set; }
        public virtual DbSet<TecnicaEscultura> TecnicaEscultura { get; set; }
        public virtual DbSet<TecnicaPintura> TecnicaPintura { get; set; }
        public virtual DbSet<Tienda> Tienda { get; set; }
        public virtual DbSet<TipoArticulo> TipoArticulo { get; set; }
        public virtual DbSet<TipoArtista> TipoArtista { get; set; }
        public virtual DbSet<TipoBoleto> TipoBoleto { get; set; }
        public virtual DbSet<TipoEdicion> TipoEdicion { get; set; }
        public virtual DbSet<TipoEmpleado> TipoEmpleado { get; set; }
        public virtual DbSet<TipoEvento> TipoEvento { get; set; }
        public virtual DbSet<TipoExhibicion> TipoExhibicion { get; set; }
        public virtual DbSet<TipoGrupo> TipoGrupo { get; set; }
        public virtual DbSet<TipoObjeto> TipoObjeto { get; set; }
        public virtual DbSet<TipoSala> TipoSala { get; set; }
        public virtual DbSet<TipoTaller> TipoTaller { get; set; }
        public virtual DbSet<TipoTienda> TipoTienda { get; set; }
        public virtual DbSet<TipoVisita> TipoVisita { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<Visitante> Visitante { get; set; }
    }
}
